[package]
name = "moodly"
version = "1.1.0"
edition = "2024"
description = "A terminal mood-tracking program."

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
csv = "1.3.1"
ctrlc = "3.4.7"
dirs = "6.0.0"
